apiVersion: v1
kind: Service
metadata:
  name: prometheus-collector
  labels:
    app: prometheus-collector
    tier: frontend
spec:
  type: NodePort
  ports:
    - name: prometheus-collector
      nodePort: 32112
      port: 2112
      protocol: TCP
      targetPort: 2112
  selector:
    app: prometheus-collector
    tier: frontend